name: Build on GitHub

on:
  push:
    branches:
      - master

jobs:
  build-then-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true

      - name: Run per se
        run: bash deploy/build_js.sh
        shell: bash

      - name: Save files
        run: |
          mkdir dist
          cp ermac.min.js src_js/third_party/jquery.min.js dist
          cp -r webassets oauth crystvis labs dist
          cp example_prod.html dist/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
